/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-variant": "#4b2947",
          "on-error-container": "#ffdad6",
          "on-secondary": "#442927",
          "on-tertiary-fixed-variant": "#404c0b",
          "on-primary-container": "#c494cc",
          "on-primary": "#472150",
          "surface-container": "#331331",
          "on-tertiary-fixed": "#181e00",
          "inverse-primary": "#794f81",
          "surface-container-highest": "#4b2947",
          "primary": "#e8b5ef",
          "on-primary-fixed-variant": "#603768",
          "error-container": "#93000a",
          "outline": "#998d97",
          "primary-container": "#522b5b",
          "secondary": "#e6bdb9",
          "surface-container-low": "#2f0f2d",
          "outline-variant": "#4d444d",
          "secondary-fixed-dim": "#e6bdb9",
          "on-secondary-container": "#d4aca8",
          "on-surface-variant": "#d0c3cd",
          "surface-tint": "#e8b5ef",
          "on-primary-fixed": "#300a3a",
          "background": "#250724",
          "primary-fixed": "#fcd6ff",
          "tertiary-fixed-dim": "#bfce80",
          "on-error": "#690005",
          "surface-dim": "#250724",
          "surface": "#250724",
          "on-secondary-fixed": "#2c1513",
          "on-surface": "#ffd7f5",
          "surface-container-high": "#3f1e3c",
          "primary-fixed-dim": "#e8b5ef",
          "on-secondary-fixed-variant": "#5d3f3d",
          "on-background": "#ffd7f5",
          "on-tertiary-container": "#9dab62",
          "surface-container-lowest": "#1f031e",
          "tertiary": "#bfce80",
          "secondary-container": "#5d3f3d",
          "error": "#ffb4ab",
          "inverse-surface": "#ffd7f5",
          "secondary-fixed": "#ffdad6",
          "inverse-on-surface": "#462443",
          "tertiary-fixed": "#dbea9a",
          "tertiary-container": "#343f00",
          "surface-bright": "#502d4c",
          "on-tertiary": "#2b3400"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "md": "24px",
          "xl": "80px",
          "sm": "16px",
          "xs": "8px",
          "base": "4px",
          "margin": "32px",
          "lg": "48px",
          "gutter": "24px"
      },
      "fontFamily": {
          "headline-xl": ["Plus Jakarta Sans"],
          "headline-lg": ["Plus Jakarta Sans"],
          "headline-md": ["Plus Jakarta Sans"],
          "headline-sm": ["Plus Jakarta Sans"],
          "body-lg": ["Plus Jakarta Sans"],
          "body-md": ["Plus Jakarta Sans"],
          "body-sm": ["Plus Jakarta Sans"],
          "label-lg": ["Plus Jakarta Sans"],
          "label-md": ["Plus Jakarta Sans"],
          "label-sm": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}
